### ISSUE TITLE
tends to match wrong packages

### ISSUE THREAD

**Issue by coderobe** [vmavromatis/absolutely-proprietary#4]
currently, the package `file` is being detected as `iscan` because parabola's blacklist description for `iscan` contains the word `file`

**Comment by vmavromatis** [comment]
Yes! That's the problem. We need to string split the files on blacklist.txt but did not have time to do it! I'm at work so I will do it later unless someone else gets me to it.

**Comment by vmavromatis** [comment]
Possible fix for this here: https://github.com/vmavromatis/absolutely-proprietary/pull/5

**Comment by vmavromatis** [comment]
Resolved with https://github.com/vmavromatis/absolutely-proprietary/pull/5!
